const FROM_NAME = "Darren";
const TO_NAME = "Keisha";

const SONG = {
  title: "sayo lang",
  artist: "shirebound (press the play button)",
  file: "sayolang.mp3",
};

const PHOTOS = [
  { src: "images/k1.jpg", caption: "my favorite picture of yours" },
  { src: "images/k2.jpg", caption: "day that reminds me of you" },
  { src: "images/k3.jpg", caption: "my baby as a baby" },
];

const REASONS = [
  "I love it when you call me by OUR endearment.",
  "I love it when you say I love you.",
  "I love the random kisses that you give.",
  "I love it when you say that you miss me.",
  "I love your eyes.",
  "I love your hair.",
  "I love your hearing your voice.",
  "I love your humor.",
  "I love your smile.",
  "I love how thoughtful you are.",
  "I love making you laugh.",
  "I love our little routines.",
  "I love playing games with you.",
  "I love you for you are so jolly.",
  "I love how your happiness is contagious.",
  "I love how you get mad at me and still talk to me. (Cold nga lang nyahaha)",
  "I love it when you boss me around in 99 Nights.",
  "I love hearing you talk about your favorite food.",
  "I love it when you tell me that you're craving something.",
  "I love the little updates that you give me.",
  "I love how compassionate you are.",
  "I love having someone I can look forward to.",
  "I love it when you run to me when things heavy.",
  "I love the idea of growing alongside you.",
  "I love how your presence can calm me down.",
  "I love speaking to you.",
  "I love it when you suddenly became my greatest blessing.",
  "I love how pure you are.",
  "I love it when you talk to me about your dreams.",
  "I love how your resilience inspires me.",
  "I love how you believe in me when I don't believe in my self.",
  "I love the way you love me so deeply.",
  "I love it when you're pakipot.",
  "I love you for how beautiful you are inside and out.",
  "I love how your energy is magnetic.",
  "I love how your heart is one of the most beautiful thing about you.",
  "I love how easy it is with you.",
  "I love how I can be a better person with you being the reason.",
  "I love how you're my favorite person to talk to.",
  "I love it when you tell me that you love me.",
  "I love how you never make me feel like a burden.",
  "I really love and acknowledge your presence.",
  "I love it when you appreciate the things that I give.",
  "I love how determined you are.",
  "I admire your perseverance.",
  "I love how you make my days very much special.",
  "I love how you make me laugh when I need it.",
  "I love making you feel seen.",
  "I love making you feel heard.",
  "I most especially love it when I make you feel loved.",
  "I like how you give importance to the things that I do for you.",
  "I love how you make me feel appreciated.",
  "I love how you make me feel that I matter.",
  "I love the fact that you still try, when things get difficult for the both of us.",
  "I love how you never make me feel like I have to pretend around you.",
  "I love how you make me feel that I'm not alone.",
  "I love it when you find ways for the things that you want",
  "I love how you work hard for what you care about.",
  "I love how you keep going when things get difficult.",
  "I love how proud you make.",
  "I love seeing the person you're becoming.",
  "I love every version of you that I've gotten to know.",
  "I love the memories we have together.",
  "I love the things that only makes sense to us.",
  "I love when you stay up longer than intended to talk to me.",
  "I love how you make me feel that I can be vulnerable around you.",
  "I love how you crack stupid jokes in the middle of serious conversations.",
  "I love knowing I get to witness you change and grow.",
  "I love how your notification pops up on my phone.",
  "I love how you make me feel special without even realizing it.",
  "I love remembering the reason why I fell for you.",
  "I love the fact that loving you can be an enjoyable hobby for me.",
  "I love imagining things that we can do in the future.",
  "I love it when you talk about places you wanna go to.",
  "I love our inside jokes.",
  "I love our made up words.",
  "I love your little habits.",
  "I love it when we get to talk to each other with the language only you and I know.",
  "I love it when you tell me about your plans in the future.",
  "I love how excited you can get about the things that you love.",
  "I love it when you tell me stories.",
  "I love it when you tell me chika about somebody that we both hate.",
  "I love your little habits.",
  "I love it when you involve me with your cousins.",
  "I love your riduculous laugh.",
  "I love it when you yap at me.",
  "I love hearing you ramble.",
  "I love how your mood lightens up when you acknowledge the assurance I give.",
  "I love how the mood lifts when we talk to each other.",
  "I love how you make me feel like I can be myself without the fear of being judged.",
  "I love how you always know what to say to make me smile.",
  "I love that you laugh at my unfunny jokes.",
  "I love how you'd complain to me about your day and I would listen to you.",
  "I love you the way you are, and I love how you make me feel loved.",
  "Mahal kita sa pamamaraan na hindi pa ipinaparamdam sa'yo ng iba.",
  "I love how you give me access to wounds and scars that you never let people see.",
  "I love hearing updates from you for things that you've accomplished the whole day.",
  "I love how you understand me in times that I need understanding.",
  " I LOVE YOU FOR WHO YOU ARE.",
  "I love the funny fact that I could list 99 reasons why I love you, but no matter how many reasons I write down, we both know that there will always be more."
];
